<?php
include_once("_inc/assets/register_assets.php");
include_once("_inc/theme/theme_setup.php");
include_once("_inc/meta-box/meta_box.php");
include_once("_inc/mr-theme-comment-body/mr_theme_comment_body.php");
include_once("helper/helper.php");
include_once("_inc/taxonimies/casts_taxonomy.php");
include_once("_inc/taxonimies/news_taxonomy.php");
include_once("_inc/subscribe/subscribe.php");
include_once("_inc/question-box/question_box.php");
include_once("_inc/admin-bar-css/style.php");
include_once("_inc/favorite-user/favorite_user.php");
include_once("_inc/profile-user-dashboard/profile_user_dashboard.php");
